# Generated by Django 5.2.17 on 2026-09-28 18:14

# Migración inicial que crea el esquema completo de la aplicación academic.
# Django la necesita para construir las tablas y relaciones en una base vacía;
# quitarla impediría aplicar el esquema mediante `manage.py migrate`.
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Marca esta migración como el inicio de la historia de cambios del esquema.
    initial = True

    # El usuario personalizado reutiliza los permisos y grupos definidos por
    # auth; sin esta dependencia podría intentarse crear antes de sus tablas.
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Categorías que organizan el catálogo de cursos; sin esta tabla los
        # cursos no podrían clasificarse por área.
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Desarrollo Web & Cloud, Inteligencia Artificial, Ciberseguridad', max_length=150, unique=True, verbose_name='Nombre del Área')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción del Área')),
                ('icono', models.CharField(default='bi-mortarboard', help_text='Clase del ícono para renderizado frontend (ej. bi-code-slash, bi-shield-lock)', max_length=50, verbose_name='Ícono Bootstrap')),
                ('activo', models.BooleanField(default=True, verbose_name='Área Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Área de Conocimiento',
                'verbose_name_plural': 'Áreas de Conocimiento',
                'db_table': 'edtech_area',
                'ordering': ['nombre'],
            },
        ),
        # Usuario del proyecto con roles, perfil y permisos de Django; sin el
        # modelo la autenticación y las relaciones con usuarios no existirían.
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('COORDINADOR', 'Coordinador Académico')], default='ESTUDIANTE', help_text='Define los permisos y nivel de acceso en la plataforma EdTech', max_length=20, verbose_name='Rol del Usuario')),
                ('rut', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT / Identificación')),
                ('telefono', models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono de Contacto')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'edtech_usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        # Carro persistente asociado uno a uno al usuario; sin la tabla no se
        # conservaría la selección de cursos entre sesiones.
        migrations.CreateModel(
            name='CarroMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro_matricula', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante Propietario')),
            ],
            options={
                'verbose_name': 'Carro de Matrícula',
                'verbose_name_plural': 'Carros de Matrícula',
                'db_table': 'edtech_carro_matricula',
            },
        ),
        # Oferta de cursos y control de cupos, vinculada a un área; sin ella no
        # existiría el catálogo ni su inventario.
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Curso / Bootcamp')),
                ('descripcion', models.TextField(verbose_name='Descripción del Programa y Objetivos')),
                ('modalidad', models.CharField(choices=[('BOOTCAMP', 'Bootcamp Intensivo'), ('CURSO', 'Curso Regular'), ('TALLER', 'Taller Especializado')], default='BOOTCAMP', max_length=20, verbose_name='Modalidad del Programa')),
                ('costo_matricula', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Matrícula ($CLP)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de Término')),
                ('cupos_totales', models.PositiveIntegerField(default=30, verbose_name='Límite Máximo de Cupos por Cohorte')),
                ('cupos_disponibles', models.PositiveIntegerField(default=30, verbose_name='Cupos Disponibles para Reserva')),
                ('imagen_url', models.CharField(blank=True, default='', max_length=300, verbose_name='URL de Imagen o Banner')),
                ('activo', models.BooleanField(default=True, verbose_name='Publicado en Catálogo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='academic.area', verbose_name='Área de Conocimiento')),
            ],
            options={
                'verbose_name': 'Curso / Bootcamp',
                'verbose_name_plural': 'Cursos y Bootcamps',
                'db_table': 'edtech_curso',
                'ordering': ['fecha_inicio', 'titulo'],
            },
        ),
        # Orden de matrícula del estudiante con total, estado e identificador;
        # sin esta tabla no se registrarían las transacciones de checkout.
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_transaccion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código Único de Transacción (UUID)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Total Pagado ($CLP)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PAGADO', max_length=20, verbose_name='Estado de la Transacción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Checkout')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización de Estado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'edtech_matricula',
                'ordering': ['-fecha_creacion'],
            },
        ),
        # Inscripciones individuales con precio histórico y ticket UUID; sin
        # ella cada matrícula perdería el detalle de cursos comprados.
        migrations.CreateModel(
            name='DetalleMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio al Momento de la Compra')),
                ('codigo_ticket', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de Ticket / Inscripción Única (UUID)')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Oficial de Inscripción')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_oficiales', to='academic.curso', verbose_name='Curso Matriculado')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='academic.matricula', verbose_name='Orden de Matrícula')),
            ],
            options={
                'verbose_name': 'Inscripción Oficial',
                'verbose_name_plural': 'Inscripciones Oficiales',
                'db_table': 'edtech_detalle_matricula',
            },
        ),
        # Cursos seleccionados en cada carro, con restricción contra duplicados;
        # sin esta tabla no se podrían guardar ni consultar sus ítems.
        migrations.CreateModel(
            name='ItemCarroMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha en que se agregó')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academic.carromatricula', verbose_name='Carro Asociado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_en_carros', to='academic.curso', verbose_name='Curso / Bootcamp')),
            ],
            options={
                'verbose_name': 'Ítem de Carro de Matrícula',
                'verbose_name_plural': 'Ítems de Carro de Matrícula',
                'db_table': 'edtech_item_carro',
                'unique_together': {('carro', 'curso')},
            },
        ),
    ]
