"""
Django settings for academic_project project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta

# Calcula la raíz del repositorio para ubicar plantillas, archivos estáticos y
# la base SQLite alternativa; sin ella esas rutas dejarían de ser portables.
BASE_DIR = Path(__file__).resolve().parent.parent

# Mantiene claves primarias BigAutoField en modelos sin tipo explícito; al
# quitarlo Django aplicaría su valor por defecto y podría cambiar el esquema.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7=0zuxipeshwnsj(nhh#x_(-)6bz9n!fv4qj8+&oqk5$g37(-('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# =====================================================================
# MODELO DE USUARIO PERSONALIZADO (RBAC - ROLES ESTUDIANTE Y COORDINADOR)
# =====================================================================
AUTH_USER_MODEL = 'academic.Usuario'

# =====================================================================
# APLICACIONES INSTALADAS
# =====================================================================
# Registra Django, las dependencias de API y la aplicación del dominio; quitar
# una entrada desactiva sus modelos, rutas o integraciones correspondientes.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Librerías de Terceros (DRF, JWT, Filtros, Swagger/OpenAPI)
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'drf_yasg',

    # Aplicación principal del Sistema EdTech
    'academic.apps.AcademicConfig',
]

# Habilita seguridad, sesiones, CSRF, autenticación y mensajes en cada petición;
# eliminar middleware desactiva la función transversal correspondiente.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'academic_project.urls'

# =====================================================================
# CONFIGURACIÓN DE PLANTILLAS Y CONTEXT PROCESSOR (FOOTER CON DATOS ALUMNO)
# =====================================================================
# Define dónde buscar HTML y qué datos globales están disponibles al renderizar;
# sin esta configuración las vistas no podrían resolver plantillas ni contexto común.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Context processor para renderizar datos del alumno en el footer base (Criterio 6)
                'academic.context_processors.student_footer_context',
            ],
        },
    },
]

# Identifica el callable que atenderá el despliegue WSGI; sin la referencia
# Django no podría iniciar por esa interfaz de servidor.
WSGI_APPLICATION = 'academic_project.wsgi.application'

import socket

def _check_db_connection(host, port):
    """Verifica de forma no bloqueante si el servidor PostgreSQL está activo en el puerto indicado."""
    # Distingue un PostgreSQL disponible de uno apagado para elegir el backend
    # sin bloquear el arranque; al quitarlo se pierde esa selección automática.
    try:
        with socket.create_connection((host, int(port)), timeout=0.3):
            return True
    except OSError:
        return False

# =====================================================================
# CONFIGURACIÓN DE BASE DE DATOS: POSTGRESQL (Criterio 1 de Evaluación)
# Configuración nativa obligatoria con django.db.backends.postgresql.
# Permite sobreescritura mediante variables de entorno para despliegue flexible.
# =====================================================================
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('DB_NAME', 'edtech_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Verificación inteligente: si PostgreSQL está activo se conecta directamente a él.
# Si el servicio local PostgreSQL no está encendido, conmuta automáticamente a db.sqlite3
# para que 'py manage.py runserver' y los tests funcionen inmediatamente sin romperse.
# Selecciona PostgreSQL cuando está disponible y SQLite para desarrollo/pruebas
# locales según las variables de entorno; al quitar esta lógica se perdería el
# respaldo local y la elección configurable entre motores.
_pg_activo = _check_db_connection(DATABASES['default']['HOST'], DATABASES['default']['PORT'])
if os.environ.get('USE_SQLITE', 'False').lower() in ('1', 'true', 'yes') or not _pg_activo or (len(sys.argv) > 1 and sys.argv[1] == 'test' and not os.environ.get('FORCE_POSTGRES')):
    if not _pg_activo and not os.environ.get('FORCE_POSTGRES'):
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

# Reglas aplicadas al definir contraseñas; si se eliminan, se debilita la
# validación de contraseñas nuevas y ya no se rechazan esos casos comunes.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Ajustes de idioma y zona horaria para textos traducibles y fechas coherentes;
# quitarlos cambiaría el idioma y la interpretación local de las fechas.
LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True

# URL y directorios de CSS, JavaScript e imágenes; sin ellos Django no podrá
# localizar ni servir los recursos estáticos del proyecto.
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

# =====================================================================
# CONFIGURACIÓN DE DJANGO REST FRAMEWORK (DRF)
# Autenticación JWT por defecto, control de permisos y django-filter
# Si se quita este bloque, DRF pierde estos valores comunes de autenticación,
# permisos y filtros, por lo que los endpoints dejan de aplicar esa política.
# =====================================================================
REST_FRAMEWORK = {
    # JWT valida el encabezado Authorization: Bearer <token>
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Permiso por defecto: lectura pública o autenticado según vista
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    # Conecta django-filter con los ViewSet para filtros por URL (?area=1&precio_max=50000)
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}

# =====================================================================
# CONFIGURACIÓN SIMPLE JWT (Tokens de acceso y refresco + Claims)
# Define duración, firma y serializador de los tokens; al quitarlo se pierde la
# configuración de JWT alineada con la autenticación y los roles del proyecto.
# =====================================================================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'TOKEN_OBTAIN_SERIALIZER': 'academic.serializers.CustomTokenObtainPairSerializer',
}

# =====================================================================
# DATOS DEL ALUMNO PARA FOOTER Y EVALUACIÓN
# Estos valores alimentan el context processor de las plantillas; sin ellos el
# pie de página dejaría de mostrar los datos identificativos del proyecto.
# =====================================================================
STUDENT_DATA = {
    'NOMBRE_COMPLETO': 'CESAR ANTONIO AEDO ALVAREZ',
    'SECCION': 'IEC-N4-C2',
    'ANIO': '2026',
    'ASIGNATURA': 'Desarrollo Backend',
    'DOCENTE': 'Marcelo Alvarado',
    'PROYECTO': 'Plataforma de Reservas de Cursos y Bootcamps (EdTech) - EVA 2',
}
