"""
Django settings for academic_project project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
import socket
from pathlib import Path
from datetime import timedelta

# Calcula la raíz del repositorio para ubicar plantillas y archivos estáticos.
BASE_DIR = Path(__file__).resolve().parent.parent

# Mantiene claves primarias BigAutoField en modelos sin tipo explícito; al
# quitarlo Django aplicaría su valor por defecto y podría cambiar el esquema.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7=0zuxipeshwnsj(nhh#x_(-)6bz9n!fv4qj8+&oqk5$g37(-('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = ['*']

# =====================================================================
# MODELO DE USUARIO PERSONALIZADO (RBAC - ROLES ESTUDIANTE Y COORDINADOR)
# =====================================================================
AUTH_USER_MODEL = 'academic.Usuario'

# =====================================================================
# APLICACIONES INSTALADAS
# =====================================================================
# Registra Django, las dependencias de API y la aplicación del dominio; quitar
# una entrada desactiva sus modelos, rutas o integraciones correspondientes.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Librerías de Terceros (DRF, JWT, Filtros, Swagger/OpenAPI)
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'drf_spectacular',

    # Aplicación principal del Sistema EdTech
    'academic.apps.AcademicConfig',
]

# Habilita seguridad, sesiones, CSRF, autenticación y mensajes en cada petición;
# eliminar middleware desactiva la función transversal correspondiente.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'academic_project.urls'

# =====================================================================
# CONFIGURACIÓN DE PLANTILLAS Y CONTEXT PROCESSOR (FOOTER CON DATOS ALUMNO)
# =====================================================================
# Define dónde buscar HTML y qué datos globales están disponibles al renderizar;
# sin esta configuración las vistas no podrían resolver plantillas ni contexto común.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Context processor para renderizar datos del alumno en el footer base (Criterio 6)
                'academic.context_processors.student_footer_context',
            ],
        },
    },
]

# Identifica el callable que atenderá el despliegue WSGI; sin la referencia
# Django no podría iniciar por esa interfaz de servidor.
WSGI_APPLICATION = 'academic_project.wsgi.application'

# Comprueba si PostgreSQL escucha en el puerto configurado para ofrecer un
# modo local de desarrollo cuando el servicio no está instalado o iniciado.
# Este chequeo no sustituye la conexión real: Django aún valida credenciales
# y disponibilidad al abrir la base de datos.
def _check_db_connection(host, port):
    try:
        with socket.create_connection((host, int(port)), timeout=0.3):
            return True
    except OSError:
        return False

# =====================================================================
# CONFIGURACIÓN DE BASE DE DATOS: POSTGRESQL (Criterio 1 de Evaluación)
# PostgreSQL es el motor predeterminado para la evaluación.
# Si no está disponible, se permite SQLite local para no bloquear el desarrollo;
# define FORCE_POSTGRES=1 para exigir PostgreSQL y hacer visibles errores de conexión.
# =====================================================================
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('DB_NAME', 'edtech_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# En pruebas se usa SQLite salvo que FORCE_POSTGRES esté habilitado.
# En ejecución normal, se conserva PostgreSQL y solo se recurre al archivo
# local cuando el servicio PostgreSQL no escucha en el host/puerto configurado.
_force_postgres = os.environ.get('FORCE_POSTGRES', '').lower() in ('1', 'true', 'yes')
_sqlite_requested = os.environ.get('USE_SQLITE', '').lower() in ('1', 'true', 'yes')
_running_tests = len(sys.argv) > 1 and sys.argv[1] == 'test'
_postgres_available = _check_db_connection(DATABASES['default']['HOST'], DATABASES['default']['PORT'])

if _sqlite_requested or (not _force_postgres and (_running_tests or not _postgres_available)):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    reason = 'USE_SQLITE está habilitado' if _sqlite_requested else (
        'ejecución de pruebas' if _running_tests else 'PostgreSQL no está disponible'
    )
    print(f'AVISO: {reason}; se usará SQLite local ({DATABASES["default"]["NAME"]}).')

# Reglas aplicadas al definir contraseñas; si se eliminan, se debilita la
# validación de contraseñas nuevas y ya no se rechazan esos casos comunes.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Ajustes de idioma y zona horaria para textos traducibles y fechas coherentes;
# quitarlos cambiaría el idioma y la interpretación local de las fechas.
LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True

# URL y directorios de CSS, JavaScript e imágenes; sin ellos Django no podrá
# localizar ni servir los recursos estáticos del proyecto.
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

# =====================================================================
# CONFIGURACIÓN DE DJANGO REST FRAMEWORK (DRF)
# Autenticación JWT por defecto, control de permisos y django-filter
# Si se quita este bloque, DRF pierde estos valores comunes de autenticación,
# permisos y filtros, por lo que los endpoints dejan de aplicar esa política.
# =====================================================================
REST_FRAMEWORK = {
    # JWT valida el encabezado Authorization: Bearer <token>
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Permiso por defecto: lectura pública o autenticado según vista
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    # Responde a las APIs de recursos en JSON, sin interfaz HTML automática del framework.
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    # Conecta django-filter con los ViewSet para filtros por URL (?area=1&precio_max=50000)
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    # Usa el generador OpenAPI con descripciones declarativas de cada operación.
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Agrupa la documentación por dominio e incorpora el esquema Bearer JWT a Swagger UI.
SPECTACULAR_SETTINGS = {
    'TITLE': 'EdTech Academy | Plataforma de Matrículas',
    'DESCRIPTION': (
        'API de catálogo académico, carro persistente, matrículas y gestión de cupos. '
        'Las operaciones indican su permiso requerido y los ejemplos de solicitud/respuesta.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'TAGS': [
        {'name': 'Autenticación', 'description': 'Registro de estudiantes y emisión/renovación de tokens.'},
        {'name': 'Áreas', 'description': 'Consulta y administración de áreas de conocimiento.'},
        {'name': 'Cursos', 'description': 'Catálogo, filtros y gestión de cursos y bootcamps.'},
        {'name': 'Carro de matrícula', 'description': 'Carro persistente del estudiante autenticado.'},
        {'name': 'Matrículas', 'description': 'Checkout, historial, consulta global y estados de matrícula.'},
    ],
}

# =====================================================================
# CONFIGURACIÓN SIMPLE JWT (Tokens de acceso y refresco + Claims)
# Define duración, firma y serializador de los tokens; al quitarlo se pierde la
# configuración de JWT alineada con la autenticación y los roles del proyecto.
# =====================================================================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'TOKEN_OBTAIN_SERIALIZER': 'academic.serializers.CustomTokenObtainPairSerializer',
}

# =====================================================================
# DATOS DEL ALUMNO PARA FOOTER Y EVALUACIÓN
# Estos valores alimentan el context processor de las plantillas; sin ellos el
# pie de página dejaría de mostrar los datos identificativos del proyecto.
# =====================================================================
STUDENT_DATA = {
    'NOMBRE_COMPLETO': 'CESAR ANTONIO AEDO ALVAREZ',
    'SECCION': 'IEC-N4-C2',
    'ANIO': '2026',
    'ASIGNATURA': 'Desarrollo Backend',
    'DOCENTE': 'Marcelo Alvarado',
    'PROYECTO': 'Plataforma de Reservas de Cursos y Bootcamps (EdTech) - EVA 2',
}
